name: Generate README on Tags Change

on:
  pull_request_target:
    branches:
      - main
    paths:
      - tags.yaml
  workflow_dispatch:
    inputs:
      check_all_prs:
        description: 'Check all open pull requests?'
        type: boolean
        required: false
        default: false

permissions:
  contents: write
  pull-requests: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}  # Ensure branch checkout
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 'stable'

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Run readme_app.go
        working-directory: generator
        run: |
          go run readme_app.go

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Ensure we are on the PR branch
          git checkout ${{ github.event.pull_request.head.ref }}

          git add .
          if ! git diff --staged --quiet; then
            git commit -m "Update README based on tags.yaml changes"
            git push origin ${{ github.event.pull_request.head.ref }}
          else
            echo "No changes to commit"
          fi
